version: '2'
services:
    sample-app:
        image: sample
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sample-postgresql:5432/sample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sample-postgresql:
        extends:
            file: postgresql.yml
            service: sample-postgresql
